### ISSUE TITLE
With newest public beta (v1.6.106) tickbox is throwing an error

### ISSUE THREAD

**Issue by nwfistere** [nwfistere/VSMenuModHelper#11]
**Exception:**
System.MissingMethodException: Method not found: 'Void Il2CppVampireSurvivors.UI.OptionsController.AddTickBox(System.String, Boolean, Il2CppSystem.Action`1<Boolean>, Boolean)'.
   at VSMenuModHelper.TickBox.<GetElement>b__9_0(OptionsController controller)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at VSMenuModHelper.OptionsMenuController.OnBuildPage(OptionsController controller, OptionsTabType type)
   at DMD<Il2CppVampireSurvivors.UI.OptionsController::BuildPage>(OptionsController this, OptionsTabType type)
   at (il2cpp -> managed) BuildPage(IntPtr , OptionsTabType , Il2CppMethodInfo* )

**Notes:**
Recompiling with newest binaries seems to fix it with no code changes.

**Comment by nwfistere** [comment]
see tag/v1.2.0-beta
