### ISSUE TITLE
VsMenuModHelper throws trampoline error when trying to use a TickBox

### ISSUE THREAD

**Issue by LeCloutPanda** [nwfistere/VSMenuModHelper#12]
Game Version: 1.6.109
VSMenuModHelper: 1.2.0

Error: 
```cs
[04:03:56.876] [Debug_Mode] During invoking native->managed trampoline
System.MissingMethodException: Method not found: 'Void Il2CppVampireSurvivors.UI.OptionsController.AddTickBox(System.String, Boolean, Il2CppSystem.Action`1<Boolean>, Boolean)'.
   at VSMenuModHelper.TickBox.<GetElement>b__9_0(OptionsController controller)
   at VSMenuModHelper.OptionsMenuController.<>c__DisplayClass7_0.<OnBuildPage>b__2(UIElement element)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at VSMenuModHelper.OptionsMenuController.OnBuildPage(OptionsController controller, OptionsTabType type)
   at DMD<Il2CppVampireSurvivors.UI.OptionsController::BuildPage>(OptionsController this, OptionsTabType type)
   at (il2cpp -> managed) BuildPage(IntPtr , OptionsTabType , Il2CppMethodInfo* )
   ```
   
   
I've attached [Latest.log](https://github.com/nwfistere/VSMenuModHelper/files/12777737/Latest.log)

**Comment by baesik** [comment]
This issue was mentioned in #11. Maybe [this version](https://github.com/nwfistere/VSMenuModHelper/releases/tag/v1.2.0-beta) will solve the issue?
